# Generated by Django 5.2.14 on 2026-05-11 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('needs_review', 'Needs Review'), ('resolved', 'Resolved'), ('error', 'Error')], db_index=True, default='queued', max_length=20)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('ocr_name_raw', models.CharField(blank=True, max_length=255)),
                ('ocr_id_raw', models.CharField(blank=True, max_length=50)),
                ('ocr_id_clean', models.CharField(blank=True, max_length=10)),
                ('name_crop', models.ImageField(null=True, upload_to='crops/')),
                ('id_crop', models.ImageField(null=True, upload_to='crops/')),
                ('top_candidates', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('match_method', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('auto_resolved', 'Auto Resolved'), ('needs_review', 'Needs Review'), ('resolved', 'Resolved')], default='needs_review', max_length=20)),
                ('resolved_manually', models.BooleanField(default=False)),
                ('added_manually', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='documents.analysisjob')),
                ('resolved_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'ordering': ['job_id', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='MonthBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_label', models.CharField(max_length=7)),
                ('month_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
            ],
            options={
                'ordering': ['-month_date', '-created_at'],
                'unique_together': {('department', 'month_label')},
            },
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.monthbatch'),
        ),
        migrations.CreateModel(
            name='HPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
                ('document_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.documentrow')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hp_records', to='employees.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.analysisjob')),
                ('month_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.monthbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'month_date'], name='documents_h_employe_860ef2_idx'), models.Index(fields=['department', 'month_date'], name='documents_h_departm_af4a1a_idx')],
            },
        ),
    ]
