# Generated by Django 5.2.14 on 2026-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrow',
            name='unresolvable',
            field=models.BooleanField(default=False),
        ),
    ]
