# Generated by Django 5.2.14 on 2026-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentrow_unresolvable'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrow',
            name='is_task_leader',
            field=models.BooleanField(default=False),
        ),
    ]
